export const tweetsDatas = [   

    {   name:"Ashish Lotake",
    handle: `@ashish02lotake`,
    profilePic: `images/ashish.png`,
    likes: 1,
    retweets: 11,
    views: '20',
    tweetText: `This is a simple twitter clone, try it out.`,
    replies: [],
    isLiked: false,
    isRetweeted: false,
    uuid: "5ab1d7e1-7c99-4de8-be88-8bcfdfb76423",
    }, 

    {   name:"Scrimba",
        handle: `@scrimba`,
        profilePic: `images/scrimbalogo.png`,
        likes: 7200,
        retweets: 6900,
        views: '500',
        tweetText: `Scrimba has the best frontend developer course in the world, check out more at scrimba.com`,
        replies: [
        { 
            name:"Elon Musk ✅",
            handle: `@Elon`,
            profilePic: `images/musk.png`,
            tweetText: `🌎 World? I would say in Milky way 🌌`,
        },
        { 
            name:"StackOver flower",
            handle: `@StackOverflower ☣️`,
            profilePic: `images/overflow.png`,
            tweetText: `Obviosuly!. I thought it's universally accepted fact`,
        },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '80f883a0-1611-484c-b9e2-68a955f90ae8',
    }, 
    {   name:"Troll Bot 💎",
        handle: `@TrollBot66756542`,
        profilePic: `images/troll.jpg`,
        likes: 27,
        retweets: 10,
        views: '500',
        tweetText: `Buy Bitcoin, ETH Make 💰💰💰 low low prices. 
            Guaranteed return on investment. HMU DMs open!!`,
        replies: [],
        isLiked: false,
        isRetweeted: false,
        uuid: '4b161eee-c0f5-4545-9c4b-8562944223ee',
    },    
    {   name:"Elon Musk ✅",
        handle: `@Elon`,
        profilePic: `images/musk.png`,
        likes: 650,
        retweets: 234,
        views: '1K',
        tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀`,
        replies: [
                  { name:"Tom Cruise ✅",
                handle: `@TomCruise`,
                profilePic: `images/tcruise.png`,
                tweetText: `Yes! Sign me up! 😎🛩`,
            },
                  { name:"Chuck Norris ✅",
                handle: `@ChuckNorris `,
                profilePic: `images/chucknorris.jpeg`,
                tweetText: `I went last year😴`,
            },

        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '3c23454ee-c0f5-9g9g-9c4b-77835tgs2',
    },
        {   name:"Noob Coder",
        handle: `@NoobCoder12`,
        profilePic: `images/flower.png`,
        likes: 10,
        retweets: 3,
        views: '50',
        tweetText: `Are you a coder if you only know HTML?`,
        replies: [
            {   name:"StackOver flower",
                handle: `@StackOverflower ☣️`,
                profilePic: `images/overflow.png`,
                tweetText: `No. Obviosuly not. Go get a job in McDonald's.`,
            },
            {   name:"Yummy Coder",
                handle: `@YummyCoder64`,
                profilePic: `images/love.png`,
                tweetText: `You are wonderful just as you are! ❤️`,
            },
        ],
        isLiked: false,
        isRetweeted: false,
        uuid: '8hy671sff-c0f5-4545-9c4b-1237gyys45',
    },     
]